<?xml version="1.0"?>
<!-- BUILD.XML complex commandline 2.6 build that copies files to website for upload. -->
<!-- Build with ANT postzip jet -->
<!-- Compile and jar commandline using ANT -->
<!-- Invoke with [ant clean] to erase class files and start over. -->
<!-- Invoke with [ant compile] to just compile. -->
<!-- Invoke with [ant jar] to compile and create jar files. -->
<!-- Invoke with [ant postjar] to post jars to the mindprod website. -->
<!-- Invoke with [ant zip] to create source code zip files. -->
<!-- Invoke with [ant postzip] to post zip file to the mindprod website. -->
<!-- Using Apache ANT version 1.10.1 -->
<!-- For details of ANT use, see http://mindprod.com/jgloss/ant.html -->
<!-- This script does not build any *.asm files. -->

<!-- D E F I N I T I O N S -->
<!-- ANT.project.dir is com/mindprod/commandline -->
<!-- basedir is E:/ -->
<project name="commandline" basedir="E:/" default="jar">

<!-- extensions for zip. Case sensitive! Go in zip, not necessarily in Jar. -->
<property name="distributed.exts" value="**/*.au,**/*.asm,**/*.bat,**/*.btm,**/*.c,**/*.COM,**/*.com,**/*.cpp,**/*.css,**/*.csv,**/*.dll,**/*.gif,**/*.h,**/*.hpp,**/*.htm,**/*.html,**/*.ico,**/*.ION,**/*.ion,**/*.jar,**/*.java,**/*.jnlp,**/*.JNLP,**/*.jpg,**/*.look,**/*.png,**/*.properties,**/*.ser,**/*.sln,**/*.txt,**/*.use,**/*.xml" />

<!-- dirs we to exclude from zip. Case sensitive! -->
<property name="nondistributed" value="**/javadoc/**,**/jetpdb/**,**/Debug/**,**/Release/**" />

<!-- C L E A N -->
<target name="clean">
<echo message="    :::    commandline    :::    deleting files to force regeneration." />
  <delete>
    <fileset dir="com/mindprod/commandline" includes="**/*.class" />
    <fileset dir="com/mindprod/commandline" includes="**/*.jar" />
    <!-- leave Jet *.exe. Old versions are still useful during the build. -->
    <fileset dir="com/mindprod/commandline" includes="commandline26.zip" />
  </delete>
</target>

<!-- C O M P I L E -->
<target name="compile">
<echo message="    :::    commandline    :::    compiling Java tree with target=1.8" />
  <javac source="1.8" target="1.8" srcdir="com/mindprod/commandline" sourcepath="${basedir}" classpath="${basedir}" encoding="UTF-8" debug="on" includeAntRuntime="false">
    <compilerarg value="-Xlint:unchecked" />
    <compilerarg value="-Xlint:fallthrough" />
    <compilerarg value="-Xlint:deprecation" />
    <compilerarg value="-Xlint:cast" />
  </javac>
</target>

<!-- J A V A H must do ant javah to rebuild *.h files. -->
<target name="javah" depends="compile">
  <!-- there is no jni -->
</target>

<!-- G A T H E R -->
<target name="gather" depends="compile">
<echo message="    :::    commandline    :::    gathering files to build jar/zip." />
  <!-- prepare commandline.use precis from two pieces -->
    <concat destfile="com/mindprod/commandline/commandline.use" fixlastline="yes">
      <filelist dir="com/mindprod/commandline" files="version.txt,use.txt,versionhistory.txt" />
    </concat>
    <copy file="E:/mindprod/application/commandline.html" todir="com/mindprod/commandline" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/application/commandline.manual.html" todir="com/mindprod/commandline" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/image/ico/commandline.ico" tofile="E:/mindprod/application/commandline.ico" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/image/icon128/commandline.png" tofile="com/mindprod/commandline/commandline.icon128.png" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/image/icon16/commandline.png" tofile="com/mindprod/commandline/commandline.icon16.png" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/image/icon32/commandline.png" tofile="com/mindprod/commandline/commandline.icon32.png" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/image/icon48/commandline.png" tofile="com/mindprod/commandline/commandline.icon48.png" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/image/icon64/commandline.png" tofile="com/mindprod/commandline/commandline.icon64.png" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/image/screenshot/commandline.png" tofile="com/mindprod/commandline/commandline.screenshot.png" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/jdisplay.css" todir="com/mindprod/commandline" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/mindprod.css" todir="com/mindprod/commandline" failonerror="false" quiet="true" overwrite="true" />
    <copy file="E:/mindprod/pad/commandline.xml" todir="com/mindprod/commandline" failonerror="false" quiet="true" overwrite="true" />
</target>

<!-- J A R -->
<!-- Make F:\Program Files (x86)\apache-ant-1.10.1\lib\GenJar.jar known to ANT -->
<!-- See http://mindprod.com/jgloss/genjar.html for details -->
<taskdef resource="genjar.properties" />

<target name="jar" depends="gather">
<echo message="    :::    commandline    :::    genjar finding dependencies and creating jar." />
  <genjar jarfile="com/mindprod/commandline/commandline.jar">
    <!-- include all classes in the package -->
    <class>
      <fileset dir="${basedir}">
        <!-- include all the classes in com/mindprod/commandline -->
        <include name="com/mindprod/commandline/*.class" />
        <!-- all dependent classes will be automatically included -->
      </fileset>
    </class>
  </genjar>

  <!-- J A R C H E C K -->
  <exec executable="jarcheck.exe" dir="com/mindprod/commandline" output="nul:" logError="true" failonerror="true">
    <arg value="commandline.jar" />
    <arg value="1.2" />
    <arg value="1.8" />
  </exec>
  <!-- J A R L O O K -->
  <exec executable="jarlook.exe" dir="com/mindprod/commandline" output="com/mindprod/commandline/commandline.look">
    <arg value="commandline.jar" />
  </exec>
</target>

<!-- P O S T J A R -->
<target name="postjar" depends="jar">
  <!-- nothing to do -->
</target>

<!-- J E T  -->
<!-- Dummy. Not using Jet -->
<target name="jet">
</target>

<!-- Z I P -->
<target name="zip" depends="jar">
<echo message="    :::    commandline    :::    preparing zip distributable." />
  <!-- Remove references to separate foot files. -->
  <exec executable="prunefoot.exe" failifexecutionfails="false" dir="com/mindprod/commandline">
    <arg value="commandline.html" />
    <arg value="commandline.manual.html" />
  </exec>
  <zip destfile="com/mindprod/commandline/commandline26.zip" duplicate="preserve" filesonly="true" includes="${distributed.exts}" excludes="${nondistributed}">
    <!-- zipfileset includes all subdirs as well -->
    <zipfileset dir="com/mindprod/commandline" prefix="com/mindprod/commandline" includes="${distributed.exts}" excludes="${nondistributed}" />
    <!-- Extra classes and properties to include in the Zip -->
      <zipfileset dir="com/mindprod/common18"    prefix="com/mindprod/common18"    includes="${distributed.exts}" excludes="${nondistributed}" />
      <zipfileset dir="com/mindprod/fastcat"     prefix="com/mindprod/fastcat"     includes="${distributed.exts}" excludes="${nondistributed}" />
      <zipfileset dir="com/mindprod/filter"    prefix="com/mindprod/filter"   includes="${distributed.exts}" excludes="${nondistributed}" />
      <zipfileset dir="com/mindprod/hunkio"    prefix="com/mindprod/hunkio"   includes="${distributed.exts}" excludes="${nondistributed}" />
  </zip>

  <!-- Z I P L O O K -->
  <exec executable="jarlook.exe" dir="com/mindprod/commandline" output="com/mindprod/commandline/zip.look">
    <arg value="commandline26.zip" />
  </exec>
</target>

<!-- P O S T Z I P -->
<target name="postzip" depends="zip,postjar">
<echo message="    :::    commandline    :::    posting zip to website." />
  <!-- copy precis to website -->
  <copy file="com/mindprod/commandline/commandline.use" tofile="E:/mindprod/precis/commandline.txt" overwrite="true" />
  <!-- copy com\mindprod\commandline/commandline26.zip to website -->
  <copy file="com\mindprod\commandline/commandline26.zip" todir="E:/mindprod/zips" overwrite="true" />
  <!-- delete old zip distributable from project and website -->
  <delete file="com/mindprod/commandline/commandline25.zip" failonerror="false" quiet="true" />
  <delete file="E:/mindprod/zips/commandline25.zip" failonerror="false" quiet="true" />
</target>
</project>
